/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `material2020` (
  `mid` int(10) NOT NULL AUTO_INCREMENT,
  `material` varchar(50) NOT NULL,
  `neg` varchar(5) DEFAULT NULL,
  `material_acc` varchar(50) NOT NULL,
  `materialcode` varchar(20) NOT NULL,
  `shaft` varchar(10) NOT NULL,
  `shaftindicator` varchar(5) DEFAULT NULL,
  `category` varchar(20) DEFAULT NULL,
  `Shape_Code` varchar(20) DEFAULT NULL,
  `tabletype` varchar(2) DEFAULT NULL,
  `company` varchar(10) NOT NULL,
  `ismaterial` varchar(5) NOT NULL,
  `haveimage` varchar(5) NOT NULL DEFAULT 'no',
  `imagesource` varchar(20) DEFAULT NULL,
  `machiningcode` int(10) DEFAULT NULL,
  `materialtype` varchar(10) DEFAULT NULL,
  `phhstandard` varchar(5) DEFAULT NULL,
  `listing` varchar(5) NOT NULL,
  `stocklisting` varchar(5) NOT NULL DEFAULT 'no',
  `subcategory` varchar(20) DEFAULT NULL,
  `combine` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`mid`)
) ENGINE=MyISAM AUTO_INCREMENT=2076 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

/*!40000 ALTER TABLE `material2020` DISABLE KEYS */;
INSERT INTO `material2020` (`mid`, `material`, `neg`, `material_acc`, `materialcode`, `shaft`, `shaftindicator`, `category`, `Shape_Code`, `tabletype`, `company`, `ismaterial`, `haveimage`, `imagesource`, `machiningcode`, `materialtype`, `phhstandard`, `listing`, `stocklisting`, `subcategory`, `combine`) VALUES
	(1, 'KD21 - Plate (DC 53)', 'yes', 'KD21 - Plate', 'kd21p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'kd21.png', 3, 'ts', 'yes', 'yes', 'yes', NULL, NULL),
	(2, 'KD11S - Plate (SKD11)', NULL, 'KD11S - Plate', 'kd11sp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'kd11s.png', 3, 'ts', 'yes', 'yes', 'yes', NULL, NULL),
	(3, 'KRCX - Plate (GO5)', 'yes', 'KRCX - Plate', 'krcxp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'krcx.png', 3, 'ts', 'yes', 'yes', 'yes', 'coldwork', NULL),
	(4, '1.2379 - Plate (SKD 11)', NULL, '1.2379 - Plate', '12379p', 'no', NULL, 'PLATE', 'PLATEN', 'E', 'PST', 'yes', 'yes', '12379.png', 3, 'ts', 'yes', 'yes', 'yes', 'coldwork', NULL),
	(5, '1.2510 - Plate (SKS 3)', NULL, '1.2510 - Plate', '12510p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', '12510.png', 2, 'ts', 'yes', 'yes', 'yes', 'coldwork', NULL),
	(6, 'KDA1S - Plate (SKD61)', NULL, 'KDA1S - Plate', 'kda1sp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'kda1s.png', 3, 'ts', 'yes', 'yes', 'yes', 'hotwork', NULL),
	(7, 'STAR80 - Plate (NAK80)', 'yes', 'STAR80 - Plate', 'star80p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'star80.png', 5, 'ts', 'yes', 'yes', 'yes', 'plasticmould', NULL),
	(8, '1.2738HH - Plate', NULL, '1.2738HH - Plate', '12738hhp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', '12738hh.png', 4, 'ts', 'yes', 'yes', 'yes', NULL, NULL),
	(9, '1.2738 - Plate', NULL, '1.2738 - Plate', '12738p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 4, 'ts', 'yes', 'yes', 'yes', 'plasticmould', NULL),
	(10, 'KPM30', 'yes', 'KPM30', 'kpm30p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'kpm30.png', 3, 'ts', 'yes', 'yes', 'yes', 'plasticmould', NULL),
	(11, '1.2311 - Plate', NULL, '1.2311 - Plate', '12311p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', '12311.png', 3, 'ts', 'yes', 'yes', 'yes', 'plasticmould', NULL),
	(12, 'PM23 - Plate (DEX20)', 'yes', 'PM23 - Plate', 'pm23p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'pm23.png', 3, 'ts', 'yes', 'yes', 'yes', 'coldwork', NULL),
	(13, 'PM23 - Harden Plate', NULL, 'PM23 - Harden Plate', 'pm23hp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(14, 'KPMAX (S55C)', NULL, 'KPMAX', 'kpmax', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'kpmax.png', 1, 'ts', 'yes', 'yes', 'yes', 'plasticmould', NULL),
	(15, '1050 - Plate (R) (S50C)', NULL, '1050 - Plate (R)', '1050p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', '1050.png', 1, 'ts', 'yes', 'yes', 'yes', 'machinerysteel', 'p1'),
	(16, '1050 - Plate (RP) (S50C)', NULL, '1050 - Plate (RP)', '1050rpp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'no', 'yes', '1050.png', 1, 'ts', 'yes', 'yes', 'no', 'machinerysteel', 'p1'),
	(17, '1050 - Sq Bar', NULL, '1050 - Sq Bar', '1050sbp', 'no', NULL, 'ROD', 'SS', 'C', 'PST', 'yes', 'no', NULL, 1, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(18, '1050 - Polish Sq Bar', NULL, '1050 - Polish Sq Bar', '1050psbp', 'no', NULL, 'ROD', 'SS', NULL, 'PST', 'yes', 'no', NULL, 1, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(19, '1050 - Flat Bar', NULL, '1050 - Flat Bar', '1050fbp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 1, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(20, '440C - Plate', NULL, '440C - Plate', '440cp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'ts', 'yes', 'yes', 'yes', 'plasticmould', NULL),
	(21, '705 - Plate', NULL, '705 - Plate', '705p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', 'machinerysteel', NULL),
	(22, '709 - Plate', NULL, '709 - Plate', '709p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', 'machinerysteel', NULL),
	(23, 'ST52 - Plate', NULL, 'ST52 - Plate', 'st52p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(24, 'High Speed Steel Plate', NULL, 'High Speed Steel Plate', 'hssp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(1001, 'SKH-51 High Speed Steel', NULL, 'SKH-51 High Speed Steel', 'skh51hss', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(25, 'GHX-VAR (Starvax)', 'yes', 'GHX-VAR', 'ghxvar', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'yes', 'plasticmould', NULL),
	(670, 'Noga', NULL, 'Noga', 'noga', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'yes', 'coldwork', NULL),
	(678, 'KD11 Max', NULL, 'KD11 Max', 'kd11max', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'yes', 'coldwork', NULL),
	(1005, 'KDAMAX', NULL, 'KDAMAX', 'kdamax', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'yes', 'hotwork', NULL),
	(711, 'HK-15', NULL, 'HK-15', 'hk15p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, NULL, 'graphite', 'yes', 'yes', 'yes', NULL, NULL),
	(712, 'HK-2', NULL, 'HK-2', 'hk2p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, NULL, 'graphite', 'yes', 'yes', 'yes', NULL, NULL),
	(713, 'HK-75', NULL, 'HK-75', 'hk75p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, NULL, 'graphite', 'yes', 'yes', 'yes', NULL, NULL),
	(716, 'HK-6 Blk', NULL, 'HK-6 Blk', 'hk6blkp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'graphite', 'no', 'yes', 'no', NULL, NULL),
	(673, '1.2316 - Plate', NULL, '1.2316 - Plate', '12316p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(688, '1050 Off Cut Plate', NULL, '1050 Off Cut Plate', '1050ocp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(1011, '1.2379 Off Cut Plate', NULL, '1.2379 Off Cut Plate', '12379ocp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(1022, 'SKH9 - Plate', NULL, 'SKH9 - Plate', 'skh9p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(26, 'KD21 - Shaft', NULL, 'KD21 - Shaft', 'kd21s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(27, 'SKD61 - Shaft **', NULL, 'SKD61 - Shaft **', 'kda1ss', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(28, 'STAR80 - Shaft', NULL, 'STAR80 - Shaft', 'star80s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(29, '1.2379 - Shaft', NULL, '1.2379 - Shaft', '12379s', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(30, '1.2510 - Shaft', NULL, '1.2510 - Shaft', '12510s', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(31, '1.2510 - Polish Shaft', NULL, '1.2510 - Polish Shaft', '12510ps', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(32, '1.2738 - Shaft', NULL, '1.2738 - Shaft (718)', '12738s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(33, '1.2311 - Shaft', NULL, '1.2311 - Shaft', '12311s', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(34, 'PM23- Shaft', NULL, 'PM23- Shaft', 'pm23s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(35, '1050 - Shaft', NULL, '1050 - Shaft', '1050s', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(36, '1050 - Polish Shaft', NULL, '1050 - Polish Shaft', '1050ps', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(37, '1050 - Hollow Pipe', NULL, '1050 - Hollow Pipe', '1050hwps', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(1010, '1050 - Hexagon', NULL, '1050 - Hexagon', '1050hxs', 'yes', 'Hex', 'ROD', 'HEX', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(38, '1020 - Shaft', NULL, '1020 - Shaft', '1020s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(39, '440C - Shaft', NULL, '440C - Shaft', '440cs', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(40, '705 - Shaft', NULL, '705 - Shaft', '705s', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(681, '705 - Hexagon', NULL, '705 - Hexagon', '705hns', 'yes', 'Hex', 'ROD', 'HEX', 'K', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(41, '709 - Shaft', NULL, '709 - Shaft', '709s', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(42, '709 - Hexagon', NULL, '709 - Hexagon', '709hns', 'yes', 'Hex', 'ROD', 'HEX', 'K', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(682, '760 - Hexagon', NULL, '760 - Hexagon', '760hns', 'yes', 'Hex', 'ROD', 'HEX', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(43, 'ST52 - Shaft', NULL, 'ST52 - Shaft', 'st52s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(703, '2316 - Shaft', NULL, '2316 - Shaft', '2316s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(715, '1045 - Shaft', NULL, '1045 - Shaft', '1045s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(990, '2083 - Shaft', NULL, '2083 - Shaft', '2083s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(44, '7210 - Shaft', NULL, '7210 - Shaft', '7210s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(1014, '7225 - Shaft', NULL, '7225 - Shaft', '7225s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(45, 'SKD11 - Shaft', NULL, 'SKD11 - Shaft', 'skd11s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(46, '9CrWMn - Shaft', NULL, '9CrWMn - Shaft', '9crwmns', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(47, 'SCM440 - Shaft', NULL, 'SCM440 - Shaft', 'scm440s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(671, 'SKH9 - Shaft', NULL, 'SKH9 - Shaft', 'skh9s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(48, 'Silver Steel Rod', NULL, 'Silver Steel Rod', 'ssrds', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(49, 'High Speed Steel Shaft', NULL, 'High Speed Steel Shaft', 'hsss', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(50, 'Starvax Shaft', NULL, 'Starvax Shaft', 'starvaxshaft', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(51, 'Own Material', NULL, 'Own Material', 'ownmat', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'no', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(52, 'Ramax', NULL, 'Ramax', 'ramax', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1021, 'Ramax Shaft', NULL, 'Ramax Shaft', 'ramaxshaft', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(695, 'Ravnex', NULL, 'Ravnex', 'ravnex', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(53, 'P20M', NULL, 'P20M', 'p20mp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1012, 'DEX 40', NULL, 'DEX 40', 'dex40p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(991, 'CPM 10V', NULL, 'CPM 10V', 'cpm10v', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(54, 'KRUPP 7218', NULL, 'KRUPP 7218', 'krupp7218p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(55, 'HSS-SKH9', NULL, 'HSS-SKH9', 'hssskh9p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(56, 'BMO 30 Plate', NULL, 'BMO 30 Plate', 'bmo30p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1004, 'XAR 400', NULL, 'XAR 400', 'xar400p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2024, 'XAR 450', NULL, 'XAR 450', 'xar450p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2025, 'XAR 500', NULL, 'XAR 500', 'xar500p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1019, 'K390', NULL, 'K390', 'k390p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(687, 'EN 24', NULL, 'EN 24', 'en24p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2021, 'DF2 PG Plate', NULL, 'DF2 PG Plate', 'df2pgp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(704, 'S355 J2', NULL, 'S355 J2', 's355j2p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1015, '17-4PH SS', NULL, '17-4PH SS', 's174phss', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'sus', 'no', 'yes', 'no', NULL, NULL),
	(1020, 'C1020B OFCuP', NULL, 'C1020B OFCuP', 'c1020bofcup', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2018, 'Elbow Short Raduis 1D', NULL, 'Elbow Short Raduis 1D', 'ewstrs1d', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(700, 'A106 Pipe', NULL, 'A106 Pipe', 'a106pipe', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1017, 'POM White', NULL, 'POM White', 'pomwhitep', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1023, 'POM Black', NULL, 'POM Black', 'pomblackp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1018, 'Titanium', NULL, 'Titanium', 'Titanium', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(57, 'Cast Iron', NULL, 'Cast Iron', 'castiron', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(58, 'Cast Iron Shaft', NULL, 'Cast Iron Shaft', 'castironshaft', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1024, 'Cast Nylon', NULL, 'Cast Nylon', 'castnylon', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(1025, 'PVC Shaft', NULL, 'PVC Shaft', 'pvcshaft', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2028, 'Teflon', NULL, 'Teflon', 'teflonp', 'no', '', 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(59, 'Wire Rod (Japan)', NULL, 'Wire Rod (Japan)', 'werdjps', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(60, 'Mould Base', NULL, 'Mould Base', 'mbse', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(61, 'Weldox 700', NULL, 'Weldox 700', 'wdx700p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(62, '3D Modelling', NULL, '3D Modelling', '3dmdlg', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(63, 'Starvax', NULL, 'Starvax', 'starvax', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'ts', 'no', 'no', 'no', NULL, NULL),
	(64, 'Cut to:', NULL, 'Cut to:', 'cttopst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(65, 'Manual Cutting', NULL, 'Manual Cutting', 'mlcgpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(66, 'CNC Cutting', NULL, 'CNC Cutting', 'cccgpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(67, 'Plasma Cutting', NULL, 'Plasma Cutting', 'pacgpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(68, 'Laser Cutting', NULL, 'Laser Cutting', 'lrcgpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(69, 'Shreading', NULL, 'Shreading', 'shrgpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(993, 'Cutting Charges', NULL, 'Cutting Charges', 'cgcspst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(70, 'Bending Charges', NULL, 'Bending Charges', 'bgcspst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(71, 'Oxy Cut', NULL, 'Oxy Cut', 'oyctpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(72, 'Bandsaw Cut', NULL, 'Bandsaw Cut', 'bwctpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(73, 'Transportation', NULL, 'Transportation', 'transportationpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(74, 'Air Freight Charges', NULL, 'Air Freight Charges', 'arftcs', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(732, 'MS Plate (Normal - R)', NULL, 'MS Plate (Normal - R)', 'mspenp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'plate', 'p1'),
	(733, 'MS Plate (Normal - RP)', NULL, 'MS Plate (Normal - RP)', 'mspenrp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'no', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'plate', 'p1'),
	(734, 'MS Plate (Profile - R)', NULL, 'MS Plate (Profile - R)', 'mspepp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'no', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'plate', 'p1'),
	(735, 'MS Plate (Profile - RP)', NULL, 'MS Plate (Profile - RP)', 'mspeprp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'no', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'plate', 'p1'),
	(736, 'MS Flat', NULL, 'MS Flat', 'msftp', 'no', NULL, 'PLATE', 'FLAT', 'A', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(737, 'MS Polish Flat (mm)', NULL, 'MS Polish Flat (mm)', 'mspfmmp', 'no', NULL, 'PLATE', 'FLAT', 'A', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(738, 'MS Polish Flat (in)', NULL, 'MS Polish Flat (in)', 'mspfinp', 'no', NULL, 'PLATE', 'FLAT', 'A', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(739, 'MS Square', NULL, 'MS Square', 'mssqp', 'no', NULL, 'ROD', 'SS', 'A', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(740, 'MS Polish Sq (mm)', NULL, 'MS Polish Sq (mm)', 'mspsmmp', 'no', NULL, 'ROD', 'SS', 'A', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(741, 'MS Polish Sq (in)', NULL, 'MS Polish Sq (in)', 'mspsinp', 'no', NULL, 'ROD', 'SS', 'A', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(742, 'MS Angle', NULL, 'MS Angle', 'msalp', 'no', NULL, 'ROD', 'A', 'B', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(1002, 'MS Unequal Angle', NULL, 'MS Unequal Angle', 'msualp', 'no', NULL, 'ROD', 'A', NULL, 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(743, 'MS Channel', NULL, 'MS Channel', 'msclp', 'no', NULL, 'ROD', 'C', 'B', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(744, 'MS C Channel', NULL, 'MS C Channel', 'mscclp', 'no', NULL, 'ROD', 'C', NULL, 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(745, 'MS Lip Channel', NULL, 'MS Lip Channel', 'mslpclp', 'no', NULL, 'ROD', 'LIP', NULL, 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(746, 'MS SHS', NULL, 'MS SHS', 'msshsp', 'yes', NULL, 'TUBE', 'HS', 'B', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(747, 'MS RHS', NULL, 'MS RHS', 'msrhsp', 'yes', NULL, 'TUBE', 'HS', 'B', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(748, 'MS Chequered Plate', NULL, 'MS Chequered Plate', 'mscpp', 'no', NULL, 'PLATE', 'PLATEN', 'G', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(749, 'MS Hot Rolled', NULL, 'MS Hot Rolled', 'mshrp', 'no', NULL, 'PLATE', 'PLATEN', 'G', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(750, 'MS Hot Rolled (Profile)', NULL, 'MS Hot Rolled (Profile)', 'mshrpp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(751, 'MS Cold Rolled', NULL, 'MS Cold Rolled', 'mscrp', 'no', NULL, 'PLATE', 'PLATEN', 'G', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(752, 'MS GI Plate', NULL, 'MS GI Plate', 'msgpp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(753, 'MS SCH 40', NULL, 'MS SCH 40', 'mss40p', 'yes', NULL, 'TUBE', 'HP', 'C', 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(754, 'MS SCH 60', NULL, 'MS SCH 60', 'mss60p', 'yes', NULL, 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(755, 'MS SCH 80', NULL, 'MS SCH 80', 'mss80p', 'yes', NULL, 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(756, 'MS SCH 160', NULL, 'MS SCH 160', 'mss160p', 'yes', NULL, 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, 1, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(757, 'MS Black Shaft', NULL, 'MS Black Shaft', 'msbss', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'shaft', 's1'),
	(758, 'MS Polish Shaft (mm)', NULL, 'MS Polish Shaft (mm)', 'mshsmms', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'shaft', 's2'),
	(759, 'MS Polish Shaft (inch)', NULL, 'MS Polish Shaft (inch)', 'mshsins', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'shaft', 's2'),
	(760, 'MS Hexagon', NULL, 'MS Hexagon', 'mshns', 'yes', 'Hex', 'ROD', 'HEX', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(761, 'MS Free Cutting Hex (mm)', NULL, 'MS Free Cutting Hex (mm)', 'msfchs', 'yes', 'Hex', 'ROD', 'HEX', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(762, 'MS Free Cutting Hex (in)', NULL, 'MS Free Cutting Hex (in)', 'msfchins', 'yes', 'Hex', 'ROD', 'HEX', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(763, 'MS Free Cutting Shaft', NULL, 'MS Free Cutting Shaft', 'msfcss', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(764, 'MS Hollow Pipe', NULL, 'MS Hollow Pipe', 'mshps', 'yes', 'Dia', 'TUBE', 'HP', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(765, 'MS Black Pipe (AA)', NULL, 'MS Black Pipe (AA)', 'msbpaas', 'yes', 'Dia', 'TUBE', 'HP', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(766, 'MS Black Pipe (A)', NULL, 'MS Black Pipe (A)', 'msbpas', 'yes', 'Dia', 'TUBE', 'HP', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(767, 'MS Black Pipe (B)', NULL, 'MS Black Pipe (B)', 'msbpbs', 'yes', 'Dia', 'TUBE', 'HP', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(768, 'MS Black Pipe (C)', NULL, 'MS Black Pipe (C)', 'msbpcs', 'yes', 'Dia', 'TUBE', 'HP', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(769, 'MS GI Pipe (A)', NULL, 'MS GI Pipe (A)', 'msgpas', 'yes', 'Dia', 'TUBE', 'HP', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(770, 'MS GI Pipe (B)', NULL, 'MS GI Pipe (B)', 'msgpbs', 'yes', 'Dia', 'TUBE', 'HP', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(771, 'MS GI Pipe (C)', NULL, 'MS GI Pipe (C)', 'msgpcs', 'yes', 'Dia', 'TUBE', 'HP', 'I', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(772, 'MS I-Beam', NULL, 'MS I-Beam', 'msims', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(773, 'MS Stud', NULL, 'MS Stud', 'studs', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(994, 'MS Perforated Plate', NULL, 'MS Perforated Plate', 'mspfdp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(774, 'MS Furniture Pipe', NULL, 'MS Furniture Pipe', 'msfepes', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'no', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(989, 'MS Thread Rod', NULL, 'MS Thread Rod', 'mstdrd', 'yes', 'Dia', NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(775, 'Brass Plate', NULL, 'Brass Plate', 'bspep', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'brass', NULL, 'yes', 'no', NULL, NULL),
	(776, 'Brass Square', NULL, 'Brass Square', 'bssqp', 'no', NULL, 'ROD', 'SS', 'A', 'PST', 'yes', 'no', NULL, 3, 'brass', NULL, 'yes', 'no', NULL, NULL),
	(777, 'Brass Flat', NULL, 'Brass Flat', 'bsftp', 'no', NULL, 'PLATE', 'FLAT', 'A', 'PST', 'yes', 'no', NULL, 3, 'brass', NULL, 'yes', 'no', NULL, NULL),
	(778, 'Brass Shim', NULL, 'Brass Shim', 'brsm', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'brass', NULL, 'yes', 'no', NULL, NULL),
	(779, 'Brass Shaft', NULL, 'Brass Shaft', 'bssts', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'brass', NULL, 'yes', 'no', NULL, NULL),
	(780, 'Brass Hexagon', NULL, 'Brass Hexagon', 'bshns', 'yes', 'Hex', 'ROD', 'HEX', 'I', 'PST', 'yes', 'no', NULL, NULL, 'brass', NULL, 'yes', 'no', NULL, NULL),
	(781, 'Brass Pipe', NULL, 'Brass Pipe', 'bspes', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'brass', NULL, 'yes', 'no', NULL, NULL),
	(782, 'Copper Plate', NULL, 'Copper Plate', 'crpep', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'plate', NULL),
	(783, 'Copper Flat', NULL, 'Copper Flat', 'crftp', 'no', NULL, 'PLATE', 'PLATEN', 'E', 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'flat', NULL),
	(784, 'Copper Square', NULL, 'Copper Square', 'crsqp', 'no', NULL, 'ROD', 'SS', 'E', 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(785, 'Copper Shim', NULL, 'Copper Shim', 'crsm', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(786, 'Tungsen Copper Plate', NULL, 'Tungsen Copper Plate', 'tncrp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(787, 'Copper Shaft', NULL, 'Copper Shaft', 'crsts', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', NULL, NULL, 'copper', NULL, 'yes', 'no', 'shaft', NULL),
	(788, 'Copper Pipe', NULL, 'Copper Pipe', 'crpis', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(789, 'Tungsen Copper Shaft', NULL, 'Tungsen Copper Shaft', 'tncrs', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(790, 'Chromium Copper', NULL, 'Chromium Copper', 'crcm', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'plate', NULL),
	(791, 'Beryllium Copper', NULL, 'Beryllium Copper', 'crbms', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'plate', NULL),
	(792, 'Beryllium Copper Shaft', NULL, 'Beryllium Copper Shaft', 'crbmsts', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(793, 'EOM Copper', NULL, 'EOM Copper', 'eomcpp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(1016, 'EDM Copper Shaft', NULL, 'EDM Copper Shaft', 'edmcs', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(794, 'Copper Material', NULL, 'Copper Material', 'cprml', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(1009, 'Copper 101', NULL, 'Copper 101', 'cr101p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(2022, 'Copper Coil', NULL, 'Copper Coil', 'crcoilp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'copper', NULL, 'yes', 'no', 'etc', NULL),
	(795, 'HNS303 Plate', NULL, 'HNS303 Plate', 'ss303p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'sus', 'yes', 'yes', 'yes', 'plate', 'p1'),
	(796, 'SUS303 Shaft', NULL, 'SUS303 Shaft', 'sssts', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'shaft', 's1'),
	(797, 'SUS303 Hexagon', NULL, 'SUS303 Hexagon', 'sus303hs', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'shaft', NULL),
	(798, 'SUS303 G', NULL, 'SUS303 G', 'sus303gp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(799, 'SUS303 Round Bar (Center Less)', NULL, 'SUS303 Round Bar (CenLes)', 'sus303rbcl', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(800, 'SUS304 Plate', NULL, 'SUS304 Plate', 'sspep', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'sus304.png', 3, 'sus', 'yes', 'yes', 'yes', 'plate', 'p2'),
	(801, 'SUS304 Plate (1B)', NULL, 'SUS304 Plate (1B)', 'ss3041bp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(802, 'SUS304 Plate (2B)', NULL, 'SUS304 Plate (2B)', 'ss3042bp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(803, 'SUS304 Plate (4B)', NULL, 'SUS304 Plate (4B)', 'ss3044bp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(804, 'SUS304 Plate Hairline', NULL, 'SUS304 Plate Hairline', 'ss304pehrp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(805, 'SUS304 Flat', NULL, 'SUS304 Flat', 'ssftp', 'no', NULL, 'PLATE', 'FLAT', 'F', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(806, 'SUS304 Flat (1B)', NULL, 'SUS304 Flat (1B)', 'ss304ftp1bp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(807, 'SUS304 Flat Hairline', NULL, 'SUS304 Flat Hairline', 'ssfthrp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(808, 'SUS304 Square', NULL, 'SUS304 Square', 'sssqp', 'no', NULL, 'ROD', 'SS', 'F', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(809, 'SUS304 Square (2B)', NULL, 'SUS304 Square (2B)', 'ss304sq2bp', 'no', NULL, 'ROD', 'SS', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(810, 'SUS304 Angle', NULL, 'SUS304 Angle', 'ssalp', 'no', NULL, 'ROD', 'A', 'L', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(811, 'SUS304 Channel', NULL, 'SUS304 Channel', 'ssclp', 'no', NULL, 'ROD', 'C', 'A', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(812, 'SUS304 SHS', NULL, 'SUS304 SHS', 'ssshsp', 'yes', NULL, 'TUBE', 'HS', 'B', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(813, 'SUS304 RHS', NULL, 'SUS304 RHS', 'ssrhsp', 'yes', NULL, 'TUBE', 'HS', 'B', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(814, 'SUS304 Chequered Plate', NULL, 'SUS304 Chequered Plate', 'sscpp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(815, 'SUS304 SCH 10', NULL, 'SUS304 SCH 10', 'ss304s10p', 'yes', NULL, 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(816, 'SUS304 SCH 40', NULL, 'SUS304 SCH 40', 'ss304s40p', 'yes', NULL, 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(817, 'SUS304 Mirror', NULL, 'SUS304 Mirror', 'ss304mrp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(818, 'SUS304L Plate', NULL, 'SUS304L Plate', 'ss304lp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(997, 'SUS304 Flange PN16', NULL, 'SUS304 Flange PN16', 'ss304fpn', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(998, 'SUS304 Elbow', NULL, 'SUS304 Elbow', 'ss304ebw', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(819, 'SUS304 Shaft (mm)', NULL, 'SUS304 Shaft (mm)', 'ssstmms', 'yes', 'Dia', 'ROD', 'O', 'J', 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'shaft', 's2'),
	(820, 'SUS304 Shaft (in)', NULL, 'SUS304 Shaft (in)', 'ssstins', 'yes', 'Dia', 'ROD', 'O', 'J', 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'shaft', 's2'),
	(821, 'SUS304 Pipe', NULL, 'SUS304 Pipe', 'ss304pes', 'yes', 'Dia', 'TUBE', 'HP', 'A', 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(822, 'SUS304 Hexagon', NULL, 'SUS304 Hexagon', 'sshns', 'yes', 'Hex', 'ROD', 'HEX', 'D', 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(823, 'SUS304 Hollow', NULL, 'SUS304 Hollow', 'sshw', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(824, 'SUS304 Round Bar (Center Less)', NULL, 'SUS304 Round Bar (CenLes)', 'sus304rbcl', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(825, 'SUS310 Plate', NULL, 'SUS310 Plate', 'ss310pes', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(826, 'SUS310 Shaft', NULL, 'SUS310 Shaft', 'ss310sts', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(828, 'SUS316 Plate', NULL, 'SUS316 Plate', 'ssptp', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'sus', 'yes', 'yes', 'yes', 'plate', 'p3'),
	(829, 'SUS316 Flat Bar', NULL, 'SUS316 Flat Bar', 'ss316fbp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(830, 'SUS316 (1B)', NULL, 'SUS316 (1B)', 'ss3161bp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(831, 'SUS316 (2B)', NULL, 'SUS316 (2B)', 'ss3162bp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(838, 'SUS316 Square', NULL, 'SUS316 Square', 'ss316sqp', 'no', NULL, 'ROD', 'SS', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(840, 'SUS316 Angle', NULL, 'SUS316 Angle', 'aa316alp', 'no', NULL, 'ROD', 'A', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(841, 'SUS316 Channel', NULL, 'SUS316 Channel', 'ss316clp', 'no', NULL, 'ROD', 'C', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(842, 'SUS316 SHS', NULL, 'SUS316 SHS', 'ss316shsp', 'yes', NULL, 'TUBE', 'HS', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(843, 'SUS316 Chequered Plate', NULL, 'SUS316 Chequered Plate', 'ss316cpp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(844, 'SUS316 (No.1 Finish)', NULL, 'SUS316 (No.1 Finish)', 'ss316n1f', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(845, 'SUS316 (Forging)', NULL, 'SUS316 (Forging)', 'ss316fg', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(999, 'SUS316 Butterfly Valve', NULL, 'SUS316 Butterfly Valve', 'ss316byve', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(2019, 'SUS316 SCH 10', NULL, 'SUS316 SCH 10', 'ss316sch10p', 'yes', NULL, 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(2020, 'SUS316 SCH 40', NULL, 'SUS316 SCH 40', 'ss316sch40p', 'yes', NULL, 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(846, 'SUS316 Shaft', NULL, 'SUS316 Shaft', 'sssfs', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(847, 'SUS316 Pipe', NULL, 'SUS316 Pipe', 'sspip', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(2016, 'SUS316 Hollow', NULL, 'SUS316 Hollow', 'ss316hw', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(848, 'SUS316 Hexagon', NULL, 'SUS316 Hexagon', 'ss316hns', 'yes', 'Hex', 'ROD', 'HEX', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(832, 'SUS316L Plate', NULL, 'SUS316L Plate', 'ss316lp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'plate', 'p3'),
	(833, 'SUS316L (2B)', NULL, 'SUS316L (2B)', 'ss316l2bp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(834, 'SUS316L (HL)', NULL, 'SUS316L (HL)', 'ss316lhlp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(995, 'SUS316L Flat Bar', NULL, 'SUS316L Flat Bar', 'ss316lfbp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(835, 'SUS316L Square', NULL, 'SUS316L Square', 'ss316lsqp', 'no', NULL, 'ROD', 'SS', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(836, 'SUS316L Angle', NULL, 'SUS316L Angle', 'aa316lalp', 'no', NULL, 'ROD', 'A', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(837, 'SUS316L Pipe', NULL, 'SUS316L Pipe', 'ss316lpes', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(839, 'SUS316L Square', NULL, 'SUS316L Square', 'ss316lsqp', 'no', NULL, 'ROD', 'SS', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(827, 'SUS316 Seamless Pipe', NULL, 'SUS316 Seamless Pipe', 'sssps', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'yes', 'sus316.png', NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(849, 'SUS316L Hexagon', NULL, 'SUS316L Hexagon', 'ss316lhns', 'yes', 'Hex', 'ROD', 'HEX', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(850, 'SUS316L Shaft', NULL, 'SUS316L Shaft', 'ss316ls', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(851, 'SUS410 Shaft', NULL, 'SUS410 Shaft', 'ss410s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(852, 'SUS420 Plate', NULL, 'SUS420 Plate', 'ss420p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(853, 'SUS420 Shaft', NULL, 'SUS420 Shaft', 'ss420s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(854, 'SUS440 Shaft', NULL, 'SUS440 Shaft', 'ss440s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(855, 'SUS630 Shaft', NULL, 'SUS630 Shaft', 'ss630s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(856, 'SUS630 Pipe', NULL, 'SUS630 Pipe', 'ss630pes', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(857, 'SUS Spring Plate', NULL, 'SUS Spring Plate', 'ssspp', 'no', NULL, 'ROD', 'FLAT', 'F', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(858, 'SUS Shim', NULL, 'SUS Shim', 'sssmp', 'no', NULL, 'ROD', 'FLAT', 'F', 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(859, 'SUS 17-4PH', NULL, 'SUS 17-4PH', 'ss174ph', 'yes', 'Dia', NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(860, 'SUS Ornametal Pipe', NULL, 'SUS Ornametal Pipe', 'ssops', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(861, 'SUS Stud', NULL, 'SUS Stud', 'sssdp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(862, 'SUS Wire', NULL, 'SUS Wire', 'sswire', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(987, 'SUS Perforated Plate', NULL, 'SUS Perforated Plate', 'sspfdp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(863, 'AA6061 Plate', NULL, 'AA6061 Plate', 'a6061ap', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'plate', NULL),
	(864, 'AA7075 Plate', NULL, 'AA7075 Plate', 'a7075ap', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(865, 'AA7075 Shaft', NULL, 'AA7075 Shaft', 'a7075as', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(867, 'AA5052 Shaft', NULL, 'AA5052 Shaft', 'a5052as', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(868, 'AA5052 H32', NULL, 'AA5052 H32', 'a5052ah32p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(869, 'AA5083 Plate', NULL, 'AA5083 Plate', 'a5083ap', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(870, 'AA1100 Plate', NULL, 'AA1100 Plate', 'a1100ap', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(871, 'AA2017 Plate', NULL, 'AA2017 Plate', 'a2017ap', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(872, 'AA2017 Shaft', NULL, 'AA2017 Shaft', 'a2017as', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(873, 'AA2024 Plate', NULL, 'AA2024 Plate', 'a2024ap', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(1006, 'AA3105 Chequered Plate', NULL, 'AA3105 Chequered Plate', 'a3105cpp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(874, 'AA5056B Shaft', NULL, 'AA5056B Shaft', 'a5056abs', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(875, 'AA7072 Plate', NULL, 'AA7072 Plate', 'a7072ap', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(876, 'AA6061 Flat', NULL, 'AA6061 Flat', 'amftp', 'no', NULL, 'PLATE', 'FLAT', 'A', 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'flat', NULL),
	(877, 'AA6061 Square', NULL, 'AA6061 Square', 'amsqp', 'no', NULL, 'ROD', 'SS', 'A', 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(878, 'AA6061 SHS', NULL, 'AA6061 SHS', 'amshsp', 'yes', NULL, 'TUBE', 'HS', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(879, 'AA6061 RHS', NULL, 'AA6061 RHS', 'amrhsp', 'yes', NULL, 'TUBE', 'HS', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(880, 'AA6061 Chequered Plate', NULL, 'AA6061 Chequered Plate', 'amcpp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'no', 'no', 'etc', NULL),
	(881, 'AA6061 Channel', NULL, 'AA6061 Channel', 'a6061acp', 'no', NULL, 'ROD', 'C', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(882, 'AA6061 Angle Bar', NULL, 'AA6061 Angle Bar', 'amabp', 'no', NULL, 'ROD', 'A', 'B', 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(996, 'AA6061 Unequal Angle Bar', NULL, 'AA6061 Unequal Angle Bar', 'amuabp', 'no', NULL, 'ROD', 'A', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(883, 'AA6061 Shaft', NULL, 'AA6061 Shaft', 'amsts', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'shaft', NULL),
	(1007, 'AA6061 (T6) Shaft', NULL, 'AA6061 (T6) Shaft', 'a6061t6s', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(884, 'AA6061 Pipe', NULL, 'AA6061 Pipe', 'ampes', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(885, 'AA6061 Hollow Pipe', NULL, 'AA6061 Hollow Pipe', 'amhpes', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(886, 'AA6061 Hexagon', NULL, 'AA6061 Hexagon', 'amhns', 'yes', 'Hex', 'ROD', 'HEX', 'I', 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(887, 'A6063 Flat Bar', NULL, 'A6063 Flat Bar', 'a6063fb', 'no', NULL, 'PLATE', 'FLAT', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(888, 'AA6063 SHS', NULL, 'AA6063 SHS', 'a6063ashsp', 'yes', NULL, 'TUBE', 'HS', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(889, 'AA6063 RHS', NULL, 'AA6063 RHS', 'a6063arhsp', 'yes', NULL, 'TUBE', 'HS', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(890, 'AA6063 Hollow Pipe', NULL, 'AA6063 Hollow Pipe', 'a6063apes', 'no', NULL, 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(891, 'AA6063 Angle Bar', NULL, 'AA6063 Angle Bar', 'a6063aab', 'no', NULL, 'ROD', 'A', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(892, 'AA6063 U Channel', NULL, 'AA6063 U Channel', 'a6063auc', 'no', NULL, 'ROD', 'C', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(893, 'YH52', NULL, 'YH52', 'yh52p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'plate', NULL),
	(894, '52S', NULL, '52S', 'a5052ap', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'plate', NULL),
	(895, '61S Plate', NULL, '61S Plate', '63spe', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(896, '63S-AA6063', NULL, '63S-AA6063', '63saa', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(897, '75S Plate', NULL, '75S Plate', '75spe', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(898, 'Cast Aluminium', NULL, 'Cast Aluminium', 'amctp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(899, 'Aluminium Conveyer', NULL, 'Aluminium Conveyer', 'aacyr', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(900, 'ANP79 (Alum)', NULL, 'ANP79 (Alum)', 'anp79p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(901, 'Alum Alloy 3003 H14', NULL, 'Alum Alloy 3003 H14', 'aa3003h', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(902, 'S20C Shaft', NULL, 'S20C Shaft', 's20cs', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(903, 'Bronze Plate', NULL, 'Bronze Plate', 'bepep', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'bronze', NULL, 'yes', 'no', NULL, NULL),
	(904, 'Bronze Shaft', NULL, 'Bronze Shaft', 'bests', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'bronze', NULL, 'yes', 'no', NULL, NULL),
	(905, 'Bronze Hollow', NULL, 'Bronze Hollow', 'behws', 'yes', 'Dia', 'TUBE', 'HP', 'A', 'PST', 'yes', 'no', NULL, NULL, 'bronze', NULL, 'yes', 'no', NULL, NULL),
	(906, 'Bronze', NULL, 'Bronze', 'bronze', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'bronze', NULL, 'yes', 'no', NULL, NULL),
	(907, 'Bronze Material', NULL, 'Bronze Material', 'brzml', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'bronze', NULL, 'yes', 'no', NULL, NULL),
	(908, 'Hardox 400', NULL, 'Hardox 400', 'h400dox', 'no', NULL, 'PLATE', 'FLAT', 'G', 'PST', 'yes', 'no', NULL, 3, 'hardox', NULL, 'yes', 'no', NULL, NULL),
	(909, 'Hardox 450', NULL, 'Hardox 450', 'h450dox', 'no', NULL, 'PLATE', 'FLAT', 'G', 'PST', 'yes', 'no', NULL, 3, 'hardox', NULL, 'yes', 'no', NULL, NULL),
	(910, 'Hardox 500', NULL, 'Hardox 500', 'h500dox', 'no', NULL, 'PLATE', 'FLAT', 'G', 'PST', 'yes', 'no', NULL, 3, 'hardox', NULL, 'yes', 'no', NULL, NULL),
	(911, 'AR400 Plate', NULL, 'AR400 Plate', 'arpe', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(912, 'SK5', NULL, 'SK5', 'sk5p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(913, 'P&O Plate', NULL, 'P&O Plate', 'popep', 'no', NULL, 'PLATE', 'PLATEN', 'G', 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(914, 'PE Plate', NULL, 'PE Plate', 'pepep', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(915, 'Normal Spring Plate', NULL, 'Normal Spring Plate', 'nspep', 'no', NULL, 'ROD', 'FLAT', 'F', 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(916, 'Expanded Metal', NULL, 'Expanded Metal', 'edmlp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(917, 'Round Tubes', NULL, 'Round Tubes', 'rdtss', 'yes', 'Dia', 'TUBE', 'HP', 'A', 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(918, 'API Pipe', NULL, 'API Pipe', 'appes', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(919, 'Own Material', NULL, 'Own Material', 'ownmat', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(920, 'Steel Material', NULL, 'Steel Material', 'stlml', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(921, 'BI-Metal Material', NULL, 'BI-Metal Material', 'bimml', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(922, '316 (2B)', NULL, '316 (2B)', '316b', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(1000, '275JR Universal Colomn', NULL, '275JR Universal Colomn', '275jruc', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(923, '355JR (50B)', NULL, '355JR (50B)', '355jr', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(924, '3D Modelling', NULL, '3D Modelling', '3dmdlg', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(925, 'HT Bar', NULL, 'HT Bar', 'htbars', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(926, 'Fibre Wood', NULL, 'Fibre Wood', 'fbwdp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(927, 'Fibre Cloth Sheet', NULL, 'Fibre Cloth Sheet', 'fbchst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(928, 'Fibre Rod', NULL, 'Fibre Rod', 'fbrds', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(929, 'Fibre Tubes', NULL, 'Fibre Tubes', 'fbtes', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(930, 'PU Rod', NULL, 'PU Rod', 'purds', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(931, 'Cast Iron', NULL, 'Cast Iron', 'castiron', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(932, 'Cast Iron Shaft', NULL, 'Cast Iron Shaft', 'castironshaft', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(933, 'Domex Wear 360', NULL, 'Domex Wear 360', 'dxwr', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(934, 'Titanium Expanded Metal', NULL, 'Titanium Expanded Metal', 'ttemp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(935, 'Duracon', NULL, 'Duracon', 'duracon', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(936, 'Eletro Galvanised Plate', NULL, 'Eletro Galvanised Plate', 'eogdpe', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(1003, 'Sand Blasting & Hard Chrome', NULL, 'Sand Blasting & Hard Chrome', 'sbahc', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(937, 'Domex 700', NULL, 'Domex 700', 'dmx700p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(938, 'Weldox 700', NULL, 'Weldox 700', 'wdx700p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(939, 'Mc Nylon Plate', NULL, 'Mc Nylon Plate', 'mcnnp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(940, 'Mc Ivory Sheet', NULL, 'Mc Ivory Sheet', 'mcis', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(941, 'MC703HL (Mc Nylon)', NULL, 'MC703HL (Mc Nylon)', 'mc703hlp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(942, 'Mc Nylon Blue Shaft', NULL, 'Mc Nylon Blue Shaft', 'mcnbs', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(2026, 'Mc Nylon Ivory Shaft', NULL, 'Mc Nylon Ivory Shaft', 'mcnis', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(943, 'EG Plate', NULL, 'EG Plate', 'egplate', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(944, 'White PE Shaft', NULL, 'White PE Shaft', 'wpes', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(945, 'Plywood', NULL, 'Plywood', 'plywood', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(946, 'Single Layer Air Bubble', NULL, 'Single Layer Air Bubble', 'slabe', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(947, 'Double Layer Air Bubble', NULL, 'Double Layer Air Bubble', 'dlabe', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(948, 'Bakelite Plate', NULL, 'Bakelite Plate', 'blpep', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(949, 'Bakelite Tube', NULL, 'Bakelite Tube', 'bltep', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(950, 'Bakelite Shaft (Cloth)', NULL, 'Bakelite Shaft (Cloth)', 'blscp', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(951, 'Perforate Plate', NULL, 'Perforate Plate', 'ptpep', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(952, 'PVC Plate Grey', NULL, 'PVC Plate Grey', 'ppegyp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(953, 'AB2', NULL, 'AB2', 'ab2p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(954, 'S355 J2', NULL, 'S355 J2', 's355j2p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(955, 'Trolley Track', NULL, 'Trolley Track', 'tytkp', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(956, 'Hydraulic Shaft', NULL, 'Hydraulic Shaft', 'hcsts', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(957, 'Bolt Nut', NULL, 'Bolt Nut', 'btnt', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(958, 'Acrylic', NULL, 'Acrylic', 'acrylic', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(959, 'General', NULL, 'General', 'general', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(960, 'Oxygen', NULL, 'Oxygen', 'oxygen', 'no', NULL, 'GAS', 'O2', 'H', 'PST', 'no', 'no', NULL, NULL, 'gas', NULL, 'yes', 'no', NULL, NULL),
	(961, 'Carbon Dioxide', NULL, 'Carbon Dioxide', 'carbondioxide', 'no', NULL, 'GAS', 'CO2', 'H', 'PST', 'no', 'no', NULL, NULL, 'gas', NULL, 'yes', 'no', NULL, NULL),
	(962, 'Nitrogen', NULL, 'Nitrogen', 'nitrogen', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(963, 'Acetylene', NULL, 'Acetylene', 'acetylene', 'no', NULL, 'GAS', 'HCCH', 'H', 'PST', 'no', 'no', NULL, NULL, 'gas', NULL, 'yes', 'no', NULL, NULL),
	(964, 'Argon', NULL, 'Argon', 'argon', 'no', NULL, 'GAS', 'AR', 'H', 'PST', 'no', 'no', NULL, NULL, 'gas', NULL, 'yes', 'no', NULL, NULL),
	(965, 'Purified Argon', NULL, 'Purified Argon', 'purifiedargon', 'no', NULL, 'GAS', 'AR', 'H', 'PST', 'no', 'no', NULL, NULL, 'gas', NULL, 'yes', 'no', NULL, NULL),
	(966, 'Transportation', NULL, 'Transportation', 'transportation', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(967, 'Forwarding Charges', NULL, 'Forwarding Charges', 'fwrdcrgs', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(968, 'Service Charges', NULL, 'Service Charges', 'svchrgs', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(969, 'Teflom (White Col)', NULL, 'Teflom (White Col)', 'teflom', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(970, 'Derlin', NULL, 'Derlin', 'derlin', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(971, 'White Derlin Plate', NULL, 'White Derlin Plate', 'wednpe', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(972, 'White Derlin Shaft', NULL, 'White Derlin Shaft', 'wedns', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(973, 'Black Derlin Shaft', NULL, 'Black Derlin Shaft', 'bkdnpe', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(974, 'Nylon Blue', NULL, 'Nylon Blue', 'nylonblue', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(975, 'Nylon White', NULL, 'Nylon White', 'nylonwhite', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(2017, 'Nylon 66', NULL, 'Nylon 66', 'nylon66s', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(976, 'Black Nylon Plate', NULL, 'Black Nylon Plate', 'bknnpe', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(977, 'Black Nylon Shaft', NULL, 'Black Nylon Shaft', 'bknnst', 'no', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(978, 'HMPE1000 Black', NULL, 'HMPE1000 Black', 'hmpe1000bk', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(979, 'Clear Acrylic Plate', NULL, 'Clear Acrylic Plate', 'cracpe', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(980, 'Clear Acrylic Shaft', NULL, 'Clear Acrylic Shaft', 'cracst', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(981, 'Black Acrylic (Solid)', NULL, 'Black Acrylic (Solid)', 'bkacsd', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(982, 'Strech Film', NULL, 'Strech Film', 'shfm', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(983, 'Hi-Rev Lubricants', NULL, 'Hi-Rev Lubricants', 'hrls', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(984, 'Rental', NULL, 'Rental', 'rntl', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(985, 'Deposit', NULL, 'Deposit', 'dpst', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(986, 'Daily Purchase', NULL, 'Daily Purchase', 'dypche', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(719, 'SKD11 Plate', NULL, 'SKD11 Plate', 'skd11pindo', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PTPHH', 'yes', 'no', NULL, 3, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(720, 'SKD11 Shaft', NULL, 'SKD11 Shaft', 'skd11sindo', 'yes', 'Dia', 'ROD', 'O', 'C', 'PTPHH', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(721, 'SKS3 Plate', NULL, 'SKS3 Plate', 'sks3pindo', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PTPHH', 'yes', 'no', NULL, 2, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(722, 'SKS3 Shaft', NULL, 'SKS3 Shaft', 'sks3sindo', 'yes', 'Dia', 'ROD', 'O', 'C', 'PTPHH', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(723, 'S50C Plate', NULL, 'S50C Plate', 's50cpindo', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PTPHH', 'yes', 'no', NULL, 1, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(724, 'S50C Shaft', NULL, 'S50C Shaft', 's50csindo', 'yes', 'Dia', 'ROD', 'O', 'C', 'PTPHH', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(725, 'SNCM439 Shaft', NULL, 'SNCM439 Shaft', 'sncm439sindo', 'yes', 'Dia', 'ROD', 'O', 'C', 'PTPHH', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(726, 'SCM440 Shaft', NULL, 'SCM440', 'scm440sindo', 'yes', 'Dia', 'ROD', 'O', 'C', 'PTPHH', 'yes', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(727, 'SS400 Plate (N)', NULL, 'SS400 Plate (N)', 'ss400npindo', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PTPHH', 'yes', 'no', NULL, NULL, 'ms', 'yes', 'yes', 'no', NULL, NULL),
	(728, 'SS400 Plate (P)', NULL, 'SS400 Plate (P)', 'ss400ppindo', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PTPHH', 'yes', 'no', NULL, NULL, 'ms', 'yes', 'yes', 'no', NULL, NULL),
	(729, 'SUS304 Shaft', NULL, 'SUS304 Shaft', 'sus304sindo', 'yes', 'Dia', 'ROD', 'O', 'C', 'PTPHH', 'yes', 'no', NULL, NULL, 'sus', 'yes', 'yes', 'no', NULL, NULL),
	(1008, 'Own Material', NULL, 'Own Material', 'ownmat', 'no', NULL, NULL, NULL, 'C', 'PTPHH', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(1013, 'Flame Hardent', NULL, 'Flame Hardent', 'flmhrdn', 'no', NULL, NULL, NULL, NULL, 'PTPHH', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(988, 'Custom Made Mould Base', NULL, 'Custom Made Mould Base', 'cmmb', 'no', NULL, NULL, NULL, NULL, 'PSVPMB', 'yes', 'no', NULL, NULL, 'mb', 'no', 'yes', 'no', NULL, NULL),
	(992, 'CNC Machining', NULL, 'CNC Machining', 'cncmachining', 'no', NULL, NULL, NULL, NULL, 'PSVPMB', 'yes', 'no', NULL, NULL, 'mb', 'no', 'yes', 'no', NULL, NULL),
	(2027, 'ICRW', NULL, 'ICRW', 'icrw', 'no', NULL, NULL, NULL, NULL, 'PSVPMB', 'yes', 'no', NULL, NULL, 'mb', 'no', 'yes', 'no', NULL, NULL),
	(2029, 'WHEEL STC 125 CBC5P', 'no', 'wstc125cbc5p', 'wstc125cbc5p', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, 0, 'other', 'no', 'yes', 'yes', NULL, NULL),
	(2030, 'WHEEL SKC 125 CBC5PT', 'no', 'wskc125cbc5pt', 'wskc125cbc5pt', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, 0, 'other', 'no', 'yes', 'yes', NULL, NULL),
	(2031, 'WHEEL STC150 CBC5PS2', 'no', 'wstc150cbc5ps2', 'wstc150cbc5ps2', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, 0, 'other', 'no', 'yes', 'yes', NULL, NULL),
	(2032, 'WHEEL SKC 150CBC5PT', 'no', 'wskc150cbc5pt', 'wskc150cbc5pt', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, 0, 'other', 'no', 'yes', 'yes', NULL, NULL),
	(2033, 'Water-Jet Cutting', 'no', 'waterjetcutting', 'waterjetcutting', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, 0, 'other', 'no', 'yes', 'yes', NULL, NULL),
	(2034, 'SUS304L Shaft', 'no', 'sus304lshaft', 'sus304lshaft', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, 0, 'sus', NULL, 'yes', 'no', 'shaft', NULL),
	(2035, 'KDA1 - Shaft', NULL, 'KDA1 - Shaft', 'kda1s', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'no', 'no', NULL, NULL, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(2036, '1.2311-P1 Plate', NULL, '1.2311-P1 Plate', '12311pp1', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, 3, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(2037, 'S50 CR  Plate', 'no', 'S50 CR  Plate', 's50crp', 'no', '', 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', '', 1, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(2038, 'S50 CR Shaft', 'no', 'S50 CR Shaft', 's50crs', 'yes', 'Dia', 'ROD', 'O', 'C', 'PST', 'yes', 'no', '', 1, 'ts', 'yes', 'yes', 'no', NULL, NULL),
	(2039, 'ST Machining', NULL, 'ST Machining', 'stmachining', 'no', NULL, NULL, NULL, NULL, 'PSVPMB', 'yes', 'no', NULL, NULL, 'mb', 'no', 'yes', 'no', NULL, NULL),
	(2040, 'AA 6061 T6', 'no', 'AA6061T6', 'aa6061t6', 'no', '', NULL, NULL, NULL, 'PST', 'yes', 'no', 'PST', 0, 'aa', 'yes', 'yes', 'no', NULL, NULL),
	(2041, 'Aluminum Chequered Plate', 'no', 'Aluminum Chequered Plate', 'acp', 'no', '', 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', '', 0, 'aa', 'yes', 'yes', 'no', NULL, NULL),
	(2042, 'BC 6 - Plate', 'no', 'BC 6 Plate', 'bc6p', 'no', '', 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', '', 0, 'brass', 'yes', 'yes', 'no', NULL, NULL),
	(2043, 'BC 6 - shaft', 'no', 'BC 6 - shaft', 'bc6s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', '', 0, 'brass', 'yes', 'yes', 'no', NULL, NULL),
	(2044, 'BC 6 pipe', 'no', 'BC 6 pipe', 'bc6pipe', 'yes', 'Dia', 'TUBE', 'HP', NULL, 'PST', 'yes', 'no', '', 0, 'brass', 'yes', 'yes', 'no', NULL, NULL),
	(2045, 'AA6082 Al Alloy Plate', 'no', 'AA6082', 'aa6082p', 'no', '', 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', '', 0, 'aa', 'yes', 'yes', 'no', NULL, NULL),
	(2046, '1.2083 (Mod) - Plate', 'no', '1.2083 (Mod) - Plate', '12083p', 'no', 'no', 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', '', 0, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(2047, '1.2083 ESR - Plate', 'no', '1.2083 ESR - Plate', '12083esrp', 'no', 'no', 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', '', 0, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(2048, ' 1.2316 ESR - Plate', 'no', ' 1.2316 ESR - Plate', '12316esrp', 'no', 'no', 'PLATE', 'PLATEN', NULL, 'pst', 'yes', 'no', '', 0, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(2049, 'AA 6061- T651 Plate ', 'no', 'AA6061T6', 'aa6061t651p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'plate', NULL),
	(2050, 'SUS403 Shaft', NULL, 'SUS403 Shaft', 'ss430s', 'yes', 'Dia', 'ROD', 'O', 'I', 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'shaft', 's1'),
	(2051, 'MS Seamless Pipe', NULL, 'MS Hollow Pipe', 'mslss', 'yes', 'Dia', 'TUBE', 'HP', 'C', 'PST', 'yes', 'no', NULL, NULL, 'ms', NULL, 'yes', 'no', 'etc', NULL),
	(2052, 'Hard Nylon Blue', NULL, 'Hard Nylon Blue', 'hnylonblue', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(2053, 'PE White Plate', NULL, 'PE White Plate', 'pewpep', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(2054, 'Invoice No. Adjsutment', NULL, 'Adjustment', 'adjust', 'no', NULL, NULL, NULL, NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(2055, 'SUS304 Polished Shaft', NULL, 'SUS304 Polished Shaft', 'ssstps', 'yes', 'Dia', 'ROD', 'O', 'J', 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'shaft', 's2'),
	(2056, 'AA3003 Chequered Plate', NULL, 'AA3003 Chequered Plate', 'a3003cpp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'etc', NULL),
	(2057, 'MS Hot Dip Galvanised Plate ( HDG )', NULL, 'MS Hot Dip Galvanised Plate ( HDG )', 'mshdgp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', NULL, 'yes', 'no', NULL, NULL),
	(2058, '4340QT', 'yes', '4340QT - Plate', '4340qt', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', '', 3, 'ts', 'yes', 'yes', 'yes', 'coldwork', NULL),
	(2059, '4140', 'yes', '4140 -  Plate', '4140', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'yes', '', 3, 'ts', 'yes', 'yes', 'yes', 'coldwork', NULL),
	(2060, 'Nak 55 - Shaft', NULL, 'Nak 55 - Shaft', 'nak55s', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'ts', 'no', 'yes', 'no', NULL, NULL),
	(2061, '1191 - Plate', NULL, '1191 - Plate', '1191p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'yes', '12311.png', 3, 'ts', 'yes', 'yes', 'yes', 'plasticmould', NULL),
	(2062, 'AA5053 Plate', NULL, 'AA5053 Plate', 'a5053ap', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'aluminium.png', 3, 'aa', NULL, 'yes', 'no', 'plate', NULL),
	(2063, 'SKC 100 VS(H)', NULL, 'skc100vsh', 'skc100vsh', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2064, 'DEX 40', NULL, 'DEX 40', 'dex40p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'no', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2065, 'STC 100 VS S-2 (RED POINT)', NULL, 'stc100vs', 'stc100vs', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2066, 'Cast Nylon Ivory', NULL, 'nylonivory', 'nylonivory', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'other', 'no', 'yes', 'no', NULL, NULL),
	(2067, 'Incoloy 800HT', 'yes', 'Incoloy 800HT', 'in800ht', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'yes', 'in800ht.png', 3, 'ts', 'yes', 'yes', 'yes', 'alloy', NULL),
	(2068, 'SUS430 Plate', NULL, 'SUS430 Plate', 'sus430p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'yes', 'sus430.png', 3, 'sus', 'yes', 'yes', 'yes', 'plate', 'p2'),
	(2069, 'SUS304 L Shaft ', NULL, 'SUS304 L Shaft ', 'ss304ls', 'yes', 'Dia', 'ROD', 'O', NULL, 'PST', 'yes', 'no', NULL, NULL, 'sus', NULL, 'yes', 'no', 'shaft', 's1'),
	(2070, 'SUS 304 BA Plate ', NULL, 'SUS 304 BA Plate ', 'sus304bap', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(2071, 'YH75', NULL, 'YH75', 'yh75p', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'aa', NULL, 'yes', 'no', 'plate', NULL),
	(2072, 'SUS304 Plate (2B/4B)', NULL, 'SUS304 Plate (2B/4B)', 'ss3042b4bp', 'no', NULL, 'PLATE', 'PLATEN', NULL, 'PST', 'yes', 'no', NULL, 3, 'sus', NULL, 'yes', 'no', 'etc', NULL),
	(2073, 'BESTHERMO', NULL, 'BESTHERMO', 'besthermo', 'no', NULL, NULL, NULL, NULL, 'PST', 'yes', 'no', NULL, NULL, 'plastic', 'no', 'yes', 'no', NULL, NULL),
	(2075, '7225 - Plate ', NULL, '7225 - Plate ', '7225p', 'no', NULL, 'PLATE', 'PLATEN', 'C', 'PST', 'yes', 'yes', 'kd11s.png', 3, 'ts', 'yes', 'yes', 'yes', NULL, NULL);
/*!40000 ALTER TABLE `material2020` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
