
CREATE TABLE IF NOT EXISTS `production_weight_2008` (
  `wid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `qid` int(10) unsigned NOT NULL,
  `quono` varchar(20) NOT NULL,
  `company` varchar(10) NOT NULL,
  `cid` int(10) unsigned NOT NULL,
  `quantity` int(10) NOT NULL,
  `grade` varchar(30) NOT NULL,
  `dimension` varchar(50) DEFAULT NULL,
  `process` varchar(20) DEFAULT NULL,
  `cuttingtype` varchar(20) DEFAULT NULL,
  `cncmach` decimal(20,2) DEFAULT NULL,
  `noposition` int(10) unsigned NOT NULL,
  `runningno` varchar(4) NOT NULL,
  `jobno` varchar(3) NOT NULL,
  `date_issue` date NOT NULL,
  `completion_date` date NOT NULL,
  `dateofcompletion` date DEFAULT NULL,
  `jlfor` varchar(5) NOT NULL,
  `status` varchar(10) NOT NULL,
  `date_start` date DEFAULT NULL,
  `packing` datetime DEFAULT NULL,
  `operation` int(3) NOT NULL DEFAULT 1,
  PRIMARY KEY (`wid`)
) ENGINE=InnoDB AUTO_INCREMENT=4249 DEFAULT CHARSET=utf8;